// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/images/dimmed-icon-16.png"
    | "/images/icon-16.png"
    | "/images/logo.jpeg"
    | "/manifest.json"
    | "/resources/secIdToFuncId.json"
    | "/resources/secIdToFuncName.json"
    | "/resources/test262IdToTest262.json"
    | "/sidepanel.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
